version: '2'
services:
    #nifi:
    #    image: apache/nifi:latest
    #    ports:
    #        - "8090:8080"
    zookeeper:
        image: wurstmeister/zookeeper:latest
        container_name: zookeeper
        ports:
          - 2181:2181
    kafka:
        image: wurstmeister/kafka:latest
        environment:
            KAFKA_ADVERTISED_HOST_NAME: 10.247.185.47
            KAFKA_ADVERTISED_PORT: 8092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: "topic:1:1"
        ports:
            - 8092:9092
